sonar.organization=akshmohan
sonar.projectKey=akshmohan_getting-started-todo-app

sonar.sources=backend/src,client/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=backend/spec
sonar.test.inclusions=backend/spec/**/*.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
