apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-client
  template:
    metadata:
      labels:
        app: todo-client
    spec:
      containers:
        - name: todo-client
          image: ghcr.io/akshmohan/getting-started-todo-app/todo-client:6ecd214f0f85da744f0bc853bbaf37a303780ba5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
