apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: todo-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootsecret"
  MYSQL_DATABASE: "todos"
  MYSQL_USER: "todoapp"
  MYSQL_PASSWORD: "appsecret"
